services:
  mysql:
    image: mysql:8.0
    container_name: tecflux
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tecflux_db